# Fuentes de Datos

Objetivo: cargar el CSV, revisar esquema, tipos, valores faltantes y una muestra representativa.

In [1]:

# --- Bootstrap del proyecto ---
import sys, pathlib, sklearn, numpy as np, pandas as pd, matplotlib
ROOT = pathlib.Path.cwd()
for cand in [ROOT] + list(ROOT.parents):
    if (cand / "src").is_dir():
        if str(cand) not in sys.path: sys.path.insert(0, str(cand))
        if str(cand / "src") not in sys.path: sys.path.insert(0, str(cand / "src"))
        break
print("Repo root:", cand)
print("sklearn:", sklearn.__version__, "| numpy:", np.__version__, "| pandas:", pd.__version__, "| matplotlib:", matplotlib.__version__)
import src.runtime_transforms  # asegura FunctionTransformer

Repo root: c:\Users\abela\Downloads\final\Proyecto_timely_response_CLEAN
sklearn: 1.5.1 | numpy: 2.1.3 | pandas: 2.3.2 | matplotlib: 3.10.6

In [14]:

from pathlib import Path
USER_CSV = Path("../data/quejas-clientes.csv")  # ajusta si usas tu archivo
CSV_PATH = USER_CSV
#Opciones de pandas
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.max_columns", 120)

df = pd.read_csv(CSV_PATH, sep=',', encoding='utf-8')
print("Shape:", df.shape)
df.head(5)

Shape: (28156, 14)

,Unnamed: 0,Complaint ID,Product,Sub-product,Issue,Sub-issue,State,ZIP code,Date received,Date sent to company,Company,Company response,Timely response?,Consumer disputed?
0,0,1291006,Debt collection,NaN,Communication tactics,Frequent or repeated calls,TX,76119.0,2015-03-19,2015-03-19,"Premium Asset Services, LLC",In progress,Yes,NaN
1,1,1290580,Debt collection,Medical,Cont'd attempts collect debt not owed,Debt is not mine,TX,77479.0,2015-03-19,2015-03-19,Accounts Receivable Consultants Inc.,Closed with explanation,Yes,NaN
2,2,1290564,Mortgage,FHA mortgage,"Application, originator, mortgage broker",NaN,MA,2127.0,2015-03-19,2015-03-19,RBS Citizens,Closed with explanation,Yes,Yes
3,3,1291615,Credit card,NaN,Other,NaN,CA,92592.0,2015-03-19,2015-03-19,Navy FCU,In progress,Yes,NaN
4,4,1292165,Debt collection,Non-federal student loan,Cont'd attempts collect debt not owed,Debt resulted from identity theft,NaN,43068.0,2015-03-19,2015-03-19,Transworld Systems Inc.,In progress,Yes,NaN

In [15]:

# Información general
display(pd.DataFrame({"column": df.columns, "dtype": df.dtypes.astype(str)}))
print("\nValores faltantes por columna:")
display(df.isna().sum().sort_values(ascending=False).to_frame("missing"))

                                    column    dtype
Unnamed: 0                      Unnamed: 0    int64
Complaint ID                  Complaint ID    int64
Product                            Product   object
Sub-product                    Sub-product   object
Issue                                Issue   object
Sub-issue                        Sub-issue   object
State                                State   object
ZIP code                          ZIP code  float64
Date received                Date received   object
Date sent to company  Date sent to company   object
Company                            Company   object
Company response          Company response   object
Timely response?          Timely response?   object
Consumer disputed?      Consumer disputed?   object

Valores faltantes por columna:

                      missing
Consumer disputed?      22150
Sub-issue               14945
Sub-product             10574
State                     421
ZIP code                  280
Issue                       2
Product                     0
Complaint ID                0
Unnamed: 0                  0
Date received               0
Date sent to company        0
Company                     0
Company response            0
Timely response?            0

In [16]:

# Distribución objetivo si existe
if "Timely response?" in df.columns:
    print("Distribución 'Timely response?':")
    display(df["Timely response?"].astype("string").str.strip().str.lower().value_counts(dropna=False))

Distribución 'Timely response?':

Timely response?
yes    27444
no       712
Name: count, dtype: Int64

In [17]:

# Guardar una muestra aleatoria de 1k filas para pruebas rápidas
sample_path = Path("data/samples/quick_sample.csv")
sample_path.parent.mkdir(parents=True, exist_ok=True)
df.sample(n=min(1000, len(df)), random_state=42).to_csv(sample_path, index=False)
print("Muestra guardada en:", sample_path.resolve())

Muestra guardada en: C:\Users\abela\Downloads\final\Proyecto_timely_response_CLEAN\notebooks\data\samples\quick_sample.csv